services:
  wireguard_site:
    build:
      context: .
        # network: host
      args:
        # server | site | client
        BUILD_TARGET: server
        # changeme (used on client)
        WIREGUARD_SERVER_PUBLICIP: 0.0.0.0
        LISTENING_PORT: 5060
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      #- "/dev/net/tun:/dev/net/tun"
      - "/dev/stdout:/dev/stdout"
    container_name: wireguard_site
    ports:
      - "5060:5060/udp"
    volumes:
      - /out:/out
      - ./bin:/usr/local/bin

    # environment:
    restart: always
      # command: ["/usr/local/bin/wireguard_start.sh"]
    command: ["/bin/sh"]
